terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# --- Networking: use the account's default VPC/subnet ---

data "aws_vpc" "default" {
  default = true
}

data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
}

# --- AMI: latest (standard, not minimal) Amazon Linux 2023 ---
#
# "al2023-ami-*" also matches the al2023-ami-minimal-* images, and
# most_recent frequently picks those. "al2023-ami-2023.*" only matches the
# standard image.

data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-2023.*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# --- SSH key pair: generated by Terraform, private key saved locally ---

resource "tls_private_key" "this" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "this" {
  key_name   = "ai-translation-key"
  public_key = tls_private_key.this.public_key_openssh
}

resource "local_file" "private_key" {
  content         = tls_private_key.this.private_key_pem
  filename        = "${path.module}/ai-translation-key.pem"
  file_permission = "0600"
}

# --- Security group: SSH + nginx (the only public entrypoint) ---
#
# app_port is deliberately not opened here — ai-translation is only reachable
# from nginx over the internal docker network (see docker-compose.prod.yaml),
# and from the instance itself via the 127.0.0.1-bound debug port.

resource "aws_security_group" "ai_translation" {
  name        = "ai-translation-sg"
  description = "Allow SSH and nginx traffic to the ai-translation host"
  vpc_id      = data.aws_vpc.default.id

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = var.ssh_cidr_blocks
  }

  ingress {
    description = "nginx (reverse proxy + rate limiter in front of ai-translation)"
    from_port   = var.nginx_port
    to_port     = var.nginx_port
    protocol    = "tcp"
    cidr_blocks = var.app_cidr_blocks
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# --- Database password: generated unless var.db_password is set ---
#
# Alphanumeric only: it is interpolated into the asyncpg URL
# (infrastructure/database/config.py) and into an unquoted env_file, where
# characters like @ : / $ would break parsing.

resource "random_password" "db" {
  length  = 32
  special = false
}

locals {
  use_bundled_postgres = var.db_host == ""
  db_password          = var.db_password != "" ? var.db_password : random_password.db.result

  nginx_conf = templatefile("${path.module}/nginx.conf.tpl", {
    nginx_port            = var.nginx_port
    app_port              = var.app_port
    rate_limit_rps        = var.nginx_rate_limit_rps
    rate_limit_burst      = var.nginx_rate_limit_burst
    client_max_body_size  = var.nginx_client_max_body_size
    proxy_timeout_seconds = var.nginx_proxy_timeout_seconds
  })

  # ai-translation + nginx (+ postgres unless var.db_host points elsewhere)
  # as a compose stack. Fully resolved at render time — no env-var
  # substitution happens on the instance itself.
  docker_compose_yml = templatefile("${path.module}/docker-compose.prod.yaml", {
    docker_image         = var.docker_image
    app_port             = var.app_port
    nginx_image          = var.nginx_image
    nginx_port           = var.nginx_port
    postgres_image       = var.postgres_image
    use_bundled_postgres = local.use_bundled_postgres
  })

  # Read by ai_translation.config.Settings and
  # infrastructure/database/config.py, and by the postgres image
  # (POSTGRES_*) when it is bundled. Empty optional values are left out so
  # the app falls back to its own defaults.
  app_env = join("\n", concat(
    [
      "REST_HOST=0.0.0.0",
      "REST_PORT=${var.app_port}",
      "DEV_MODE=false",
      "DEBUG=false",
      "QWEN_MODEL_NAME=${var.qwen_model_name}",
      "TRANSLATION_BATCH_SIZE=${var.translation_batch_size}",
      "DB_HOST=${local.use_bundled_postgres ? "postgres" : var.db_host}",
      "DB_PORT=${var.db_port}",
      "DB_USER=${var.db_user}",
      "DB_PASSWORD=${local.db_password}",
      "DB_NAME=${var.db_name}",
      "RATE_LIMIT=${var.app_rate_limit}",
      "CORS_ORIGINS=${var.cors_origins}",
      "CORS_ALLOW_HEADERS=${var.cors_allow_headers}",
    ],
    var.hf_token != "" ? ["HF_TOKEN=${var.hf_token}"] : [],
    local.use_bundled_postgres ? [
      "POSTGRES_USER=${var.db_user}",
      "POSTGRES_PASSWORD=${local.db_password}",
      "POSTGRES_DB=${var.db_name}",
    ] : [],
    [""],
  ))

  # Pulled into its own local so it can also be exposed via outputs.tf's
  # rendered_user_data — EC2 only runs this script on an instance's first
  # boot, so `make tf-redeploy` re-runs this exact value over SSH to roll
  # out config changes. No separate, driftable "redeploy script."
  user_data = templatefile("${path.module}/user_data.sh.tpl", {
    docker_compose_version    = var.docker_compose_version
    app_env_base64            = base64encode(local.app_env)
    nginx_conf_base64         = base64encode(local.nginx_conf)
    docker_compose_yml_base64 = base64encode(local.docker_compose_yml)
  })
}

# --- EC2 instance running ai-translation behind an nginx reverse proxy ---

resource "aws_instance" "ai_translation" {
  ami                    = data.aws_ami.al2023.id
  instance_type          = var.instance_type
  subnet_id              = data.aws_subnets.default.ids[0]
  key_name               = aws_key_pair.this.key_name
  vpc_security_group_ids = [aws_security_group.ai_translation.id]

  user_data = local.user_data

  # The image (torch + LibreOffice + fonts), the Hugging Face model cache
  # and the bundled postgres data all live on this volume.
  root_block_device {
    volume_size = var.root_volume_size
    volume_type = "gp3"
  }

  metadata_options {
    http_tokens = "required"
  }

  # A newer AMI or a changed user_data would otherwise replace/restart the
  # instance (and wipe the model cache and bundled postgres data). Config
  # changes are rolled out with `make tf-redeploy` instead.
  lifecycle {
    ignore_changes = [ami, user_data]
  }

  tags = {
    Name = "ai-translation"
  }
}

# Stable public address, so the portal's AI_TRANSLATION_API_URL survives
# instance stop/start.
resource "aws_eip" "ai_translation" {
  instance = aws_instance.ai_translation.id
  domain   = "vpc"

  tags = {
    Name = "ai-translation"
  }
}
