terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# --- Networking: use the account's default VPC/subnet ---

data "aws_vpc" "default" {
  default = true
}

data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
}

data "aws_kms_alias" "ssm" {
  name = "alias/aws/ssm"
}

# --- AMI: latest (standard, not minimal) Amazon Linux 2023 ---
#
# "al2023-ami-*" also matches the al2023-ami-minimal-* images, and
# most_recent frequently picks those. "al2023-ami-2023.*" only matches the
# standard image.

data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-2023.*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# --- SSH key pair: generated by Terraform, private key saved locally ---

resource "tls_private_key" "this" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "this" {
  key_name   = "ai-translation-key"
  public_key = tls_private_key.this.public_key_openssh
}

resource "local_file" "private_key" {
  content         = tls_private_key.this.private_key_pem
  filename        = "${path.module}/ai-translation-key.pem"
  file_permission = "0600"
}

# --- Security group: SSH + HTTP/HTTPS reverse proxy ---
#
# app_port is deliberately not opened here — ai-translation is only reachable
# from Caddy over the internal docker network (see docker-compose.prod.yaml),
# and from the instance itself via the 127.0.0.1-bound debug port.

resource "aws_security_group" "ai_translation" {
  name        = "ai-translation-sg"
  description = "Allow SSH and Caddy HTTPS traffic to the ai-translation host"
  vpc_id      = data.aws_vpc.default.id

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = var.ssh_cidr_blocks
  }

  ingress {
    description = "HTTP for ACME challenges and redirects"
    from_port   = var.http_port
    to_port     = var.http_port
    protocol    = "tcp"
    cidr_blocks = var.app_cidr_blocks
  }

  ingress {
    description = "HTTPS API reverse proxy"
    from_port   = var.https_port
    to_port     = var.https_port
    protocol    = "tcp"
    cidr_blocks = var.app_cidr_blocks
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# --- Database password: generated unless var.db_password is set ---
#
# Alphanumeric only: it is interpolated into the asyncpg URL
# (infrastructure/database/config.py) and into an unquoted env_file, where
# characters like @ : / $ would break parsing.

resource "random_password" "db" {
  length  = 32
  special = false
}

locals {
  app_secrets = jsonencode({
    PORTAL_API_TOKEN  = var.portal_api_token
    DB_PASSWORD       = local.db_password
    POSTGRES_PASSWORD = local.db_password
    HF_TOKEN          = var.hf_token
  })
}

resource "aws_ssm_parameter" "app_secrets" {
  name        = "/ai-translation/runtime-secrets"
  description = "Runtime credentials for the AI Translation EC2 service"
  type        = "SecureString"
  key_id      = data.aws_kms_alias.ssm.target_key_arn
  value       = local.app_secrets
}

resource "aws_iam_role" "ai_translation" {
  name = "ai-translation-ec2-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy" "read_app_secrets" {
  name = "read-ai-translation-runtime-secrets"
  role = aws_iam_role.ai_translation.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["ssm:GetParameter"]
        Resource = aws_ssm_parameter.app_secrets.arn
      },
      {
        Effect   = "Allow"
        Action   = ["kms:Decrypt"]
        Resource = data.aws_kms_alias.ssm.target_key_arn
        Condition = {
          StringEquals = {
            "kms:ViaService"                      = "ssm.${var.aws_region}.amazonaws.com"
            "kms:EncryptionContext:PARAMETER_ARN" = aws_ssm_parameter.app_secrets.arn
          }
        }
      }
    ]
  })
}

resource "aws_iam_instance_profile" "ai_translation" {
  name = "ai-translation-ec2-profile"
  role = aws_iam_role.ai_translation.name
}

locals {
  use_bundled_postgres = var.db_host == ""
  db_password          = var.db_password != "" ? var.db_password : random_password.db.result

  caddyfile = templatefile("${path.module}/Caddyfile.tpl", {
    api_domain = var.api_domain
    acme_email = var.acme_email
    app_port   = var.app_port
  })

  # ai-translation + Caddy (+ postgres unless var.db_host points elsewhere)
  # as a compose stack. Fully resolved at render time — no env-var
  # substitution happens on the instance itself.
  docker_compose_yml = templatefile("${path.module}/docker-compose.prod.yaml", {
    docker_image         = var.docker_image
    app_port             = var.app_port
    caddy_image          = var.caddy_image
    http_port            = var.http_port
    https_port           = var.https_port
    postgres_image       = var.postgres_image
    use_bundled_postgres = local.use_bundled_postgres
  })

  # Non-secret settings only. Runtime credentials are fetched from SSM on boot.
  app_env = join("\n", concat(
    [
      "REST_HOST=0.0.0.0",
      "REST_PORT=${var.app_port}",
      "DEV_MODE=false",
      "DEBUG=false",
      "NLLB_MODEL_NAME=${var.nllb_model_name}",
      "TRANSLATION_BATCH_SIZE=${var.translation_batch_size}",
      "DB_HOST=${local.use_bundled_postgres ? "postgres" : var.db_host}",
      "DB_PORT=${var.db_port}",
      "DB_USER=${var.db_user}",
      "DB_NAME=${var.db_name}",
      "RATE_LIMIT=${var.app_rate_limit}",
      "CORS_ORIGINS=${var.cors_origins}",
      "CORS_ALLOW_HEADERS=${var.cors_allow_headers}",
    ],
    local.use_bundled_postgres ? [
      "POSTGRES_USER=${var.db_user}",
      "POSTGRES_DB=${var.db_name}",
    ] : [],
    [""],
  ))

  # Pulled into its own local so it can also be exposed via outputs.tf's
  # rendered_user_data — EC2 only runs this script on an instance's first
  # boot, so `make tf-redeploy` re-runs this exact value over SSH to roll
  # out config changes. No separate, driftable "redeploy script."
  user_data = templatefile("${path.module}/user_data.sh.tpl", {
    docker_compose_version    = var.docker_compose_version
    aws_region                = var.aws_region
    secrets_parameter_name    = aws_ssm_parameter.app_secrets.name
    app_env_base64            = base64encode(local.app_env)
    caddyfile_base64          = base64encode(local.caddyfile)
    docker_compose_yml_base64 = base64encode(local.docker_compose_yml)
  })
}

# --- EC2 instance running ai-translation behind Caddy ---

resource "aws_instance" "ai_translation" {
  ami                    = data.aws_ami.al2023.id
  instance_type          = var.instance_type
  subnet_id              = data.aws_subnets.default.ids[0]
  key_name               = aws_key_pair.this.key_name
  vpc_security_group_ids = [aws_security_group.ai_translation.id]
  iam_instance_profile   = aws_iam_instance_profile.ai_translation.name

  user_data = local.user_data

  # The image (torch + LibreOffice + fonts), the Hugging Face model cache
  # and the bundled postgres data all live on this volume.
  root_block_device {
    volume_size = var.root_volume_size
    volume_type = "gp3"
  }

  metadata_options {
    http_tokens = "required"
  }

  # A newer AMI or a changed user_data would otherwise replace/restart the
  # instance (and wipe the model cache and bundled postgres data). Config
  # changes are rolled out with `make tf-redeploy` instead.
  lifecycle {
    ignore_changes = [ami, user_data]

    precondition {
      condition     = var.model_license_allows_production
      error_message = "Production is blocked: confirm a translation model license that permits commercial document translation before setting model_license_allows_production=true."
    }
  }

  tags = {
    Name = "ai-translation"
  }
}

# Stable public address, so the portal's AI_TRANSLATION_API_URL survives
# instance stop/start.
resource "aws_eip" "ai_translation" {
  instance = aws_instance.ai_translation.id
  domain   = "vpc"

  tags = {
    Name = "ai-translation"
  }
}
