# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: translation/v1/translation.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "translation/v1/translation.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n translation/v1/translation.proto\x12\x0etranslation.v1"|\n\x10TranslateRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x17\n\x0fsource_language\x18\x02 \x01(\t\x12\x17\n\x0ftarget_language\x18\x03 \x01(\t\x12\x14\n\x0c\x65motion_tags\x18\x04 \x03(\t\x12\x12\n\nvoice_tags\x18\x05 \x03(\t"m\n\x11TranslateResponse\x12\x17\n\x0ftranslated_text\x18\x01 \x01(\t\x12\x17\n\x0fsource_language\x18\x02 \x01(\t\x12\x17\n\x0ftarget_language\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t2f\n\x12TranslationService\x12P\n\tTranslate\x12 .translation.v1.TranslateRequest\x1a!.translation.v1.TranslateResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "translation.v1.translation_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TRANSLATEREQUEST"]._serialized_start = 52
    _globals["_TRANSLATEREQUEST"]._serialized_end = 176
    _globals["_TRANSLATERESPONSE"]._serialized_start = 178
    _globals["_TRANSLATERESPONSE"]._serialized_end = 287
    _globals["_TRANSLATIONSERVICE"]._serialized_start = 289
    _globals["_TRANSLATIONSERVICE"]._serialized_end = 391
# @@protoc_insertion_point(module_scope)
