syntax = "proto3";

package translation.v1;

option java_multiple_files = true;
option java_package = "com.sdewa.coreServices.grpc.translation.v1";
option java_outer_classname = "TranslationProto";

service TranslationService {
  rpc Translate(TranslateRequest) returns (TranslateResponse);
}

message TranslateRequest {
  string text = 1;

  string source_language = 2;
  string target_language = 3;

  repeated string emotion_tags = 4;
  repeated string voice_tags = 5;
}



message TranslateResponse {
  string translated_text = 1;

  string source_language = 2;
  string target_language = 3;

  string model = 4;
}